name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d /root/whats-organizer-front ]; then
            mkdir /root/whats-organizer-front;
          fi
          cd /root/whats-organizer-front
          git clone https://github.com/${{ github.repository }} ./
          docker compose up --build
          docker system prune --volumes -a
