name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ -d /root/whats-organizer-front ]; then
            rm -r /root/whats-organizer-front
          fi
          mkdir /root/whats-organizer-front
          cd /root/whats-organizer-front
          git clone https://github.com/${{ github.repository }} ./
          cp /root/envs/front/.env .
          cp /root/envs/front/nginx.env ./infra/server/.env
          docker compose build
          docker compose up -d
          docker system prune --volumes -a --force
